safe: true
markdown: kramdown
exclude: [ assets ]
permalink: /:title.html

default_theme: yandex
default_width: 792
default_lang: ru
default_body_class: list

kramdown:
  enable_coderay: false

presentation:
    title: "JS: Going&nbsp;deeper"
    nda: false

author:
    name: Станислав Говоров
    position: Системный инженер
    company:
        name: Яндекс
        url:  http://yandex.ru/

progress: true
